<?php
/**
 * Created 04-02-14 21:13
 */
namespace Swoopaholic\Component\Table\Type;

use Swoopaholic\Component\Table\TableInterface;
use Swoopaholic\Component\Table\TableView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class CellType extends BaseType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);

        $resolver->setDefaults(
            array(
                'value' => null
            )
        );
        $resolver->setAllowedValues(array());
        $resolver->setAllowedTypes(array());
    }

    public function buildView(TableView $view, TableInterface $table, array $options)
    {
        parent::buildView($view, $table, $options); // TODO: Change the autogenerated stub

        $view->vars['value'] = $options['value'];
    }


    public function getName()
    {
        return 'cell';
    }
}
