<?php
/**
 * Created 04-02-14 21:13
 */
namespace Swoopaholic\Component\Table\Type;

use Swoopaholic\Component\Table\TableInterface;
use Swoopaholic\Component\Table\TableView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class HeadCellType extends BaseType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);

        $resolver->setDefaults(
            array(
                'label' => '',
                'sortLink' => null,
                'sortDir' => null,
                'active' => false,
            )
        );
        $resolver->setAllowedValues(array());
        $resolver->setAllowedTypes(array());
    }

    public function buildView(TableView $view, TableInterface $table, array $options)
    {
        parent::buildView($view, $table, $options); // TODO: Change the autogenerated stub

        $view->vars['sortLink'] = $options['sortLink'];
        $view->vars['sortDir'] = $options['sortDir'];
        $view->vars['active'] = $options['active'];
        $view->vars['label'] = $options['label'];
    }

    public function getParent()
    {
        return 'cell';
    }

    public function getName()
    {
        return 'head_cell';
    }
}
